spring:
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/customers
    username: postgres
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
