spring:
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/customers
    username: postgres
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
